// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroKeyWASM.Server.Models;

namespace ZeroKeyWASM.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZeroKeyWASM.Server.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("UnitPrice");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("32b8b9f5-18d3-4099-b2a5-bd92d1772d0e"),
                            ProductName = "Book",
                            UnitPrice = 12.49m
                        },
                        new
                        {
                            ProductId = new Guid("0f047c60-b9fa-49e7-a6be-70b3a63f46c6"),
                            ProductName = "Music CD",
                            UnitPrice = 14.99m
                        },
                        new
                        {
                            ProductId = new Guid("40dcb307-591b-4506-a3a9-c922ae959d1d"),
                            ProductName = "Chocolate Bar",
                            UnitPrice = 0.85m
                        },
                        new
                        {
                            ProductId = new Guid("2532b4ce-d379-473d-b685-39cd0296375c"),
                            ProductName = "Imported Box of Chocolate",
                            UnitPrice = 10.00m
                        },
                        new
                        {
                            ProductId = new Guid("5e020105-ff60-4054-9466-5354527e08ae"),
                            ProductName = "Imported Bottle of Perfume",
                            UnitPrice = 47.50m
                        },
                        new
                        {
                            ProductId = new Guid("8067d4a7-8622-467a-846f-659c0f8e4866"),
                            ProductName = "Imported Bottle of Perfume",
                            UnitPrice = 27.99m
                        },
                        new
                        {
                            ProductId = new Guid("f46f2cbe-6121-4413-892f-e98667568598"),
                            ProductName = "Bottle of Perfume",
                            UnitPrice = 18.99m
                        },
                        new
                        {
                            ProductId = new Guid("63963b77-7e8d-47ad-b960-e0763ac1a8c8"),
                            ProductName = "Packet of Headache Pills",
                            UnitPrice = 9.75m
                        },
                        new
                        {
                            ProductId = new Guid("3e16c745-8c5b-4135-805d-b650aab3303a"),
                            ProductName = "Imported Box of Chocolate",
                            UnitPrice = 11.25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
